{% set version = "1.3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-logr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/logr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/logr/logr_{{ version }}.tar.gz
  sha256: 9566dcb34d56ad742d3ac4832b5d8b93f4d374182ea877b1a022ab19ee15ea40

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-common
    - r-withr
  run:
    - r-base
    - r-common
    - r-withr

test:
  commands:
    - $R -e "library('logr')"           # [not win]
    - "\"%R%\" -e \"library('logr')\""  # [win]

about:
  home: https://logr.r-sassy.org
  dev_url: https://github.com/dbosak01/logr
  license: CC0-1.0
  summary: Contains functions to help create log files.  The package aims to overcome the difficulty of the base R sink() command.  The log_print() function will print to both the console and the file log, without interfering in other write operations.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r
